[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         xsiam_agent
    Listen       0.0.0.0
    Port         1514
    Chunk_Size   32
    Buffer_Size  256
    Heartbeat_Min 60
    Heartbeat_Max 180
    DB_Sync true
    Arango_Host localhost
    Arango_Port 8529
    Arango_User root
    Arango_Pass changeme
    Arango_Database xsiamdb
    DB_Flush_Interval 5
    Heartbeat_Flush_Interval 180
    Tenant_ID t-super
    Event_Host 172.31.176.1
    Event_Port 18090

[OUTPUT]
    Name         stdout
    Match        *

[OUTPUT]
    Name         xsiam_log
    Match        xsiam_agent.*
    Ingest_URL   http://172.31.176.1:18090
    Tag_Field    session_protocol
    Compress_Level 3
    Max_Batch_Rows 8192
