[SERVICE]
    Flush        1
    Log_Level    info

[INPUT]
    Name         xsiam_agent
    Listen       127.0.0.1
    Port         1514
    Chunk_Size   32
    Buffer_Size  256
    Heartbeat_Min 60
    Heartbeat_Max 180
    DB_Sync true
    Arango_Host 127.0.0.1
    Arango_Port 8529
    Arango_User root
    Arango_Pass changeme
    Arango_Database xsiamdb
    DB_Flush_Interval 5
    Heartbeat_Flush_Interval 180

[OUTPUT]
    Name         stdout
    Match        *
