import { useState, useRef, useEffect } from 'react'
import type { CSSProperties } from 'react'
import type { PageMeta } from '@/lib/api'
import PageHeader from '@/components/PageHeader'

// ── Type Definitions ──────────────────────────────────────────────────────────

interface CaseItem {
  id: string
  displayId: string
  severity: 'C' | 'H' | 'M' | 'L'
  score: number
  badge?: string
  name: string
  description: string
  issueCount: number
  issueLabel: string
  sources: string[]
  extraMeta?: string[]
  status: string
}

interface ArtifactRow {
  name: string
  hash: string
  wf: boolean
  verdict: 'malware' | 'benign'
  vtScore?: string
}

interface AssetRow {
  icon: string
  name: string
  tag: 'EG' | 'R'
  badges: string[]
}

interface AlertRow {
  sev: 'High' | 'Medium' | 'Low' | 'Critical'
  source: string
  action: string
  category: string
  name: string
  description: string
  starred: boolean
}

interface MitreCell {
  count: number
  label: string
  color?: string
}

interface PolicyGroup {
  id: string
  icon: string
  label: string
  expanded: boolean
  items: string[]
}

// ── Static Data ───────────────────────────────────────────────────────────────

const CASES: CaseItem[] = [
  {
    id: 'INC5254',
    displayId: 'ID-5254',
    severity: 'H',
    score: 41,
    badge: 'Security',
    name: 'Volume Shadow Deletion Attempt',
    description: "'Volume Shadow Deletion Attempt - 1186929355' along with 16 other alerts generated by XSIAM Analytics BIOC, XSIAM Agent, PAN NGFW...",
    issueCount: 17,
    issueLabel: '17 Issues',
    sources: ['A', '⊕', '▲', '⚡'],
    status: '处理中',
  },
  {
    id: 'INC3324',
    displayId: 'ID-3324',
    severity: 'C',
    score: 93,
    name: 'EC2 Breakout and Exploitation',
    description: 'Lateral movement and unauthorized IAM actions due to a publicly exposed AWS EC2 instance with IAM management access...',
    issueCount: 31,
    issueLabel: '31 Alerts',
    sources: [],
    extraMeta: ['Cloud / AWS'],
    status: '处理中',
  },
]

const MITRE_CELLS: MitreCell[] = [
  { count: 0, label: 'Reconnaissance' },
  { count: 2, label: 'Resource\nDevelopment' },
  { count: 5, label: 'Initial Access', color: '#fa582d' },
  { count: 1, label: 'Execution' },
  { count: 0, label: 'Persistence' },
  { count: 0, label: 'Privilege\nEscalation' },
  { count: 1, label: 'Defense\nEvasion', color: '#e53935' },
  { count: 2, label: 'Credential\nAccess' },
  { count: 2, label: 'Discovery' },
  { count: 0, label: 'Lateral\nMovement' },
  { count: 1, label: 'Collection' },
  { count: 0, label: 'Command\nand Control' },
]

const ARTIFACTS: ArtifactRow[] = [
  { name: 'SonarFX (1).exe', hash: '9a55...80bc', wf: true, verdict: 'malware', vtScore: 'VT59/70' },
  { name: 'cmd.exe', hash: 'b94d...8cc4', wf: true, verdict: 'benign', vtScore: 'VT0/72' },
  { name: 'vssadmin.exe', hash: 'd757...1976', wf: true, verdict: 'benign', vtScore: 'VT0/72' },
  { name: 'chrome.exe', hash: '527f...a648', wf: true, verdict: 'benign', vtScore: 'VT0/70' },
  { name: 'conhost.exe', hash: 'ac68...90e8', wf: true, verdict: 'benign' },
]

const ASSETS: AssetRow[] = [
  { icon: '🖥', name: 'daas-01', tag: 'EG', badges: ['Cortex Labs Serv...', '+2'] },
  { icon: '🖥', name: 'dc01 ⭐', tag: 'R', badges: ['Certificate Autho...', '+4'] },
  { icon: '👤', name: 'democload\\watson', tag: 'R', badges: ['Privileged Accou...'] },
]

const ISSUE_SOURCES = [
  { label: 'XSIAM Analytics BIOC', count: 7 },
  { label: 'XSIAM Agent', count: 5 },
  { label: 'XSIAM BIOC', count: 3 },
  { label: 'XSIAM Analytics', count: 2 },
  { label: 'PAN NGFW', count: 1 },
  { label: 'Correlation', count: 1 },
]

const ALERTS: AlertRow[] = [
  { sev: 'High', source: 'PAN NGFW', action: 'Detected (Raised An Alert)', category: 'Vulnerability', name: 'HTTP-403', description: 'Vulnerability Exposure...', starred: false },
  { sev: 'High', source: 'PAN NGFW', action: 'Detected (Raised An Alert)', category: 'Vulnerability', name: 'HTTP-403 +6', description: 'Vulnerability Exposure...', starred: false },
  { sev: 'High', source: 'PAN NGFW', action: 'Detected (Raised An Alert)', category: 'Vulnerability', name: 'HTTP-403 +3', description: 'Vulnerability Exposure...', starred: false },
  { sev: 'High', source: 'PAN NGFW', action: 'Detected (Raised An Alert)', category: 'Vulnerability', name: 'HTTP-403 +12', description: 'Vulnerability Exposure...', starred: false },
  { sev: 'Medium', source: 'XSIAM Analytics BIOC', action: 'Detected', category: 'Impact', name: 'Security Event Log was cleared using wevtutil.exe', description: 'The process cmd...', starred: false },
  { sev: 'Medium', source: 'XSIAM Analytics BIOC', action: 'Detected', category: 'Impact', name: 'A Sensitive Windows was Event Log cleared using wevtutil.exe', description: 'The process cmd...', starred: false },
  { sev: 'Medium', source: 'XSIAM Agent', action: 'Detected (Reported)', category: 'Malware', name: 'Suspicious Process Creation', description: 'Suspicious proc...', starred: false },
  { sev: 'Medium', source: 'XSIAM Agent', action: 'Detected (Reported)', category: 'Malware', name: 'WildFire Malware +2', description: 'Suspicious execu...', starred: false },
  { sev: 'High', source: 'XSIAM Agent', action: 'Detected (Reported)', category: 'Malware', name: 'Credential Gathering Protection - 657061549', description: 'Mimikatz process...', starred: false },
  { sev: 'High', source: 'XSIAM BIOC', action: 'Detected', category: 'Credential Access', name: 'Command-line arguments match Mimikatz execution', description: 'Process [action...', starred: true },
  { sev: 'High', source: 'XSIAM BIOC', action: 'Detected', category: 'Credential Access', name: 'Mimikatz command-line arguments', description: 'Process [action...', starred: true },
  { sev: 'Low', source: 'XSIAM Analytics', action: 'Detected', category: 'Execution', name: 'Multiple Rare LOLBIN Process Executions by User', description: '3 LOLBIN process...', starred: false },
  { sev: 'Low', source: 'XSIAM Analytics', action: 'Detected', category: 'Discovery', name: 'Multiple discovery commands', description: 'WS-IT10 perform...', starred: false },
  { sev: 'High', source: 'XSIAM BIOC', action: 'Detected', category: 'File Type Obfuscation', name: 'Binary file being created to disk with a double extension', description: 'File [file name...', starred: false },
  { sev: 'High', source: 'PAN NGFW', action: 'Detected (Allowed The Session)', category: 'Wildfire Analysis', name: 'Windows Executable (EXE) +5', description: 'Filetype Detectio...', starred: false },
  { sev: 'High', source: 'XSIAM Agent', action: 'Detected (Reported)', category: 'Malware', name: 'Credential Gathering Protection - 2288106171', description: 'MiniDumpWrited...', starred: false },
  { sev: 'High', source: 'XSIAM Agent', action: 'Detected (Reported)', category: 'Malware', name: 'Staged Malware Activity - 4065507433', description: 'Activity similar to...', starred: false },
  { sev: 'Medium', source: 'XSIAM Analytics BIOC', action: 'Detected', category: 'Credential Access', name: 'LSASS dump file written to disk', description: '', starred: true },
]

interface TimelineEvent {
  time: string
  type: 'alert' | 'action' | 'note' | 'status' | 'assign'
  actor?: string
  text: string
  detail?: string
}

interface WarRoomMsg {
  id: number
  author: string
  avatar: string
  time: string
  text: string
  attachments?: string[]
}

interface ExecutionRow {
  id: string
  playbook: string
  trigger: string
  status: 'completed' | 'running' | 'failed'
  startedAt: string
  duration: string
  actor: string
  steps: number
  stepsOk: number
}

const TIMELINE_EVENTS: TimelineEvent[] = [
  { time: '2026-05-23 09:41', type: 'alert', text: 'WildFire Malware alert triggered on daas-01', detail: 'SonarFX (1).exe — VT 59/70' },
  { time: '2026-05-23 09:41', type: 'action', actor: 'Automation', text: 'Playbook 218359 - WildFire Malware started' },
  { time: '2026-05-23 09:42', type: 'alert', text: 'Credential Gathering Protection fired', detail: 'Mimikatz detected on daas-01' },
  { time: '2026-05-23 09:43', type: 'alert', text: 'Volume Shadow Deletion Attempt — vssadmin.exe', detail: '17 correlated alerts in this incident' },
  { time: '2026-05-23 09:44', type: 'action', actor: 'Automation', text: 'Endpoint isolation applied to daas-01' },
  { time: '2026-05-23 09:45', type: 'status', actor: 'AutoAssign', text: 'Incident assigned to analyst watson' },
  { time: '2026-05-23 09:50', type: 'note', actor: 'watson', text: 'Confirmed ransomware pre-staging activity. VSS deletion blocked. LSASS dump found on disk — escalating to IR.' },
  { time: '2026-05-23 10:02', type: 'alert', text: 'Binary file created with double extension — SonarFX.exe.pdf', detail: 'XSIAM BIOC: File Type Obfuscation' },
  { time: '2026-05-23 10:15', type: 'action', actor: 'watson', text: 'Forensic snapshot taken on daas-01' },
  { time: '2026-05-23 10:22', type: 'status', actor: 'watson', text: 'Status changed to 处理中' },
  { time: '2026-05-23 11:10', type: 'note', actor: 'ir-team', text: 'Memory dump confirms Mimikatz sekurlsa::logonpasswords execution. Lateral movement to dc01 detected via SMB.' },
  { time: '2026-05-23 11:45', type: 'action', actor: 'ir-team', text: 'Network segment blocked — dc01 quarantined' },
]

const WARROOM_MSGS: WarRoomMsg[] = [
  { id: 1, author: 'System', avatar: 'S', time: '09:41', text: 'Incident INC-5254 created: Volume Shadow Deletion Attempt (17 alerts)', attachments: [] },
  { id: 2, author: 'AutoAssign', avatar: 'A', time: '09:45', text: 'Assigned to watson based on workload balance.' },
  { id: 3, author: 'watson', avatar: 'W', time: '09:52', text: 'On it — pulling forensics from daas-01 now. Looks like pre-ransomware staging.' },
  { id: 4, author: 'ir-team', avatar: 'I', time: '10:05', text: 'Loop me in. We\'ve seen this SonarFX dropper before — Unit 42 named it "BlackShadow loader" in last week\'s advisory.' },
  { id: 5, author: 'watson', avatar: 'W', time: '10:18', text: 'Confirmed. VT 59/70. Also found LSASS dump at C:\\ProgramData\\dump.dmp — uploading to WildFire now.', attachments: ['dump.dmp (1.2 GB)'] },
  { id: 6, author: 'Automation', avatar: '⚡', time: '10:20', text: 'WildFire analysis complete — MALICIOUS. SHA256: 9a55...80bc. Scope: Credential Theft + Ransomware Pre-Stage.' },
  { id: 7, author: 'ir-team', avatar: 'I', time: '10:22', text: 'Lateral movement to dc01 confirmed via SMB. Blocking network segment now. Recommend full IR runbook.' },
  { id: 8, author: 'watson', avatar: 'W', time: '10:35', text: 'IR runbook initiated. All credentials on affected segment treated as compromised. Notifying CISO.' },
  { id: 9, author: 'Automation', avatar: '⚡', time: '11:45', text: 'Network block policy applied. dc01 quarantined. 3 playbooks completed successfully.' },
]

const EXECUTIONS: ExecutionRow[] = [
  { id: 'EX-2841', playbook: '218359 - WildFire Malware', trigger: 'Auto (Alert Match)', status: 'completed', startedAt: '2026-05-23 09:41', duration: '1m 12s', actor: 'Automation', steps: 8, stepsOk: 8 },
  { id: 'EX-2842', playbook: 'Endpoint Isolation', trigger: 'Auto (Severity ≥ High)', status: 'completed', startedAt: '2026-05-23 09:44', duration: '22s', actor: 'Automation', steps: 3, stepsOk: 3 },
  { id: 'EX-2843', playbook: 'Forensic Snapshot', trigger: 'Manual — watson', status: 'completed', startedAt: '2026-05-23 10:15', duration: '4m 55s', actor: 'watson', steps: 6, stepsOk: 6 },
  { id: 'EX-2844', playbook: 'WildFire Re-analysis', trigger: 'Manual — watson', status: 'completed', startedAt: '2026-05-23 10:18', duration: '2m 03s', actor: 'watson', steps: 4, stepsOk: 4 },
  { id: 'EX-2845', playbook: 'Network Segment Block', trigger: 'Manual — ir-team', status: 'completed', startedAt: '2026-05-23 11:45', duration: '38s', actor: 'ir-team', steps: 5, stepsOk: 5 },
  { id: 'EX-2846', playbook: 'Full IR Runbook', trigger: 'Manual — ir-team', status: 'running', startedAt: '2026-05-23 12:10', duration: '—', actor: 'ir-team', steps: 14, stepsOk: 7 },
]

const ALL_ARTIFACTS: ArtifactRow[] = [
  { name: 'SonarFX (1).exe', hash: '9a55...80bc', wf: true, verdict: 'malware', vtScore: 'VT59/70' },
  { name: 'cmd.exe', hash: 'b94d...8cc4', wf: true, verdict: 'benign', vtScore: 'VT0/72' },
  { name: 'vssadmin.exe', hash: 'd757...1976', wf: true, verdict: 'benign', vtScore: 'VT0/72' },
  { name: 'chrome.exe', hash: '527f...a648', wf: true, verdict: 'benign', vtScore: 'VT0/70' },
  { name: 'conhost.exe', hash: 'ac68...90e8', wf: true, verdict: 'benign' },
  { name: 'mimikatz.exe', hash: 'c826...3f7a', wf: true, verdict: 'malware', vtScore: 'VT68/72' },
  { name: 'lsass.dmp', hash: '71c3...b2e1', wf: false, verdict: 'malware' },
  { name: 'powershell.exe', hash: 'ae32...f9d0', wf: true, verdict: 'benign', vtScore: 'VT0/70' },
  { name: 'wevtutil.exe', hash: '9f4a...c15d', wf: true, verdict: 'benign' },
  { name: 'SonarFX.exe.pdf', hash: 'b82e...447c', wf: true, verdict: 'malware', vtScore: 'VT55/70' },
]

const ALL_ASSETS: AssetRow[] = [
  { icon: '🖥', name: 'daas-01', tag: 'EG', badges: ['Cortex Labs Serv...', '+2'] },
  { icon: '🖥', name: 'dc01 ⭐', tag: 'R', badges: ['Certificate Autho...', '+4'] },
  { icon: '👤', name: 'democload\\watson', tag: 'R', badges: ['Privileged Accou...'] },
  { icon: '🖥', name: 'wkstn-007', tag: 'EG', badges: ['Engineering'] },
  { icon: '👤', name: 'democload\\administrator', tag: 'R', badges: ['Domain Admin', '+1'] },
]

const INITIAL_POLICY_GROUPS: PolicyGroup[] = [
  {
    id: 'agent',
    icon: '👤',
    label: 'Agent Settings (Default)',
    expanded: false,
    items: [],
  },
  {
    id: 'malware',
    icon: '☠',
    label: 'Malware (Default)',
    expanded: true,
    items: [
      'Portable Executables and DLL Examination',
      'Office Files with Macros Examination',
      'PowerShell Script Files',
      'On-write File Examination',
      'ASP & ASPX Files',
      'On-demand File Examination',
      'VB Scripts Examination',
      'Global Behavioral Threat Protection Rules',
      'Credential Gathering Protection',
      'Anti Webshell Protection',
      'Financial Malware Threat Protection',
      'Cryptominers Protection',
      'In-process shellcode protection',
      'Malicious Device Prevention',
      'UAC Bypass Prevention',
      'Anti Tampering Protection',
      'IIS Protection',
      'UEFI Protection',
      'Ransomware Protection',
      'Malicious Child Process Protection',
      'Password Theft Protection',
      'Respond to Malicious Causality Chains',
      'Network Packet Inspection Engine',
      'Dynamic Kernel Protection',
      'Security Measures Bypass',
    ],
  },
  {
    id: 'exploit',
    icon: '⚡',
    label: 'Exploit (Default)',
    expanded: false,
    items: [],
  },
  {
    id: 'restrictions',
    icon: '⚙',
    label: 'Restrictions (Default)',
    expanded: false,
    items: [],
  },
  {
    id: 'exceptions',
    icon: '🚫',
    label: 'Exceptions (Default No Exceptions)',
    expanded: false,
    items: [],
  },
]

// ── Shared style helpers ──────────────────────────────────────────────────────

const SEV_PILL_BG: Record<string, string> = {
  C: 'var(--critical)',
  H: 'var(--high)',
  M: 'var(--medium)',
  L: 'var(--low)',
}

const SEV_TAG_BG: Record<string, string> = {
  High: 'var(--high)',
  Medium: 'var(--medium)',
  Low: 'var(--accent-blue)',
  Critical: 'var(--critical)',
}

function getActionDotColor(action: string): string {
  if (action.toLowerCase().includes('prevented')) return '#e53935'
  if (action.toLowerCase().includes('allowed')) return '#0078d4'
  return '#4fa3e0'
}

// ── Agentix Step type ─────────────────────────────────────────────────────────

type AgentixStep =
  | { type: 'greeting' }
  | { type: 'userMsg'; text: string }
  | { type: 'hashResult'; hash: string }
  | { type: 'plan'; hash: string }
  | { type: 'approval'; hash: string }
  | { type: 'approved'; hash: string }
  | { type: 'declined' }

// ── Main Component ─────────────────────────────────────────────────────────────

export default function XDRCases() {
  const [mainView, setMainView] = useState<'cases' | 'policy'>('cases')
  const [selectedCase, setSelectedCase] = useState<string>('INC5254')
  const [activeTab, setActiveTab] = useState<string>('overview')
  const [alertSubTab, setAlertSubTab] = useState<'alerts' | 'insights'>('alerts')
  const [agentix开放, setAgentix开放] = useState<boolean>(false)
  const [agentixInput, setAgentixInput] = useState<string>('')
  const [agentixSteps, setAgentixSteps] = useState<AgentixStep[]>([{ type: 'greeting' }])
  const [policyGroups, setPolicyGroups] = useState<PolicyGroup[]>(INITIAL_POLICY_GROUPS)
  const [selectedPolicy, setSelectedPolicy] = useState<string>('Portable Executables and DLL Examination')
  const [warRoomInput, setWarRoomInput] = useState<string>('')
  const [warRoomMsgs, setWarRoomMsgs] = useState<WarRoomMsg[]>(WARROOM_MSGS)
  const warRoomRef = useRef<HTMLDivElement>(null)

  const agentixBodyRef = useRef<HTMLDivElement>(null)

  // Scroll agentix body to bottom whenever steps change
  useEffect(() => {
    if (agentixBodyRef.current) {
      agentixBodyRef.current.scrollTop = agentixBodyRef.current.scrollHeight
    }
  }, [agentixSteps])

  // ── Agentix handlers ──

  function sendAgentix() {
    const msg = agentixInput.trim()
    if (!msg) return
    setAgentixInput('')
    const hash = '9a55f55886285eef7ffabdd55c0232d1458175b1d868c03d3e304ce7d98980bc'

    setAgentixSteps(prev => [...prev, { type: 'userMsg', text: msg }])
    setTimeout(() => {
      setAgentixSteps(prev => [...prev, { type: 'hashResult', hash }])
      setTimeout(() => {
        setAgentixSteps(prev => [...prev, { type: 'plan', hash }])
        setTimeout(() => {
          setAgentixSteps(prev => [...prev, { type: 'approval', hash }])
        }, 800)
      }, 600)
    }, 600)
  }

  function agentixApprove() {
    const hash = '9a55f55886285eef7ffabdd55c0232d1458175b1d868c03d3e304ce7d98980bc'
    setAgentixSteps(prev =>
      prev.map(s => (s.type === 'approval' ? ({ type: 'approved', hash } as AgentixStep) : s))
    )
  }

  function togglePolicyGroup(id: string) {
    setPolicyGroups(prev =>
      prev.map(g => (g.id === id ? { ...g, expanded: !g.expanded } : g))
    )
  }

  const selectedCaseData = CASES.find(c => c.id === selectedCase)

  // ── Render ──

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100vh', overflow: 'hidden', background: 'var(--bg-primary)' }}>

      {/* ── Cases View ── */}
      {mainView === 'cases' && (
        <>
          {/* Top bar */}
          <PageHeader
            title="XSIAM Cases"
            subtitle={selectedCaseData ? `${selectedCaseData.displayId} ${selectedCaseData.name}` : undefined}
            actions={<>
              <span style={{
                fontSize: 10.5, color: '#8a8fa0',
                border: '1px solid var(--border-light)',
                padding: '2px 8px', borderRadius: 3,
              }}>Managed by Unit42 Managed Services</span>
              <button
                onClick={() => { setAgentix开放(true); setAgentixSteps([{ type: 'greeting' }]) }}
                style={{
                  background: 'var(--bg-card)', border: '1px solid var(--border-light)',
                  color: 'var(--text-muted)', borderRadius: 4, padding: '4px 10px',
                  fontSize: 12, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 4,
                }}>
                <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="#0078d4" strokeWidth="2">
                  <circle cx="12" cy="12" r="10" /><path d="M12 8v4l3 3" />
                </svg>
                Agentix AI
              </button>
              <button
                onClick={() => setMainView('policy')}
                style={{
                  background: 'var(--bg-card)', border: '1px solid var(--border-light)',
                  color: 'var(--text-muted)', borderRadius: 4, padding: '4px 10px',
                  fontSize: 12, cursor: 'pointer',
                }}>Policy Management</button>
              <button
                onClick={() => {
                  const name = prompt('Case name:')
                  if (name?.trim()) alert(`Case "${name}" created.`)
                }}
                style={{
                  background: 'var(--bg-card)', border: '1px solid #00c89644',
                  color: '#0078d4', borderRadius: 4, padding: '4px 10px',
                  fontSize: 12, cursor: 'pointer',
                }}>+ 新建案例</button>
            </>}
          />

          {/* Body */}
          <div style={{ flex: 1, display: 'flex', overflow: 'hidden', minHeight: 0 }}>

            {/* Left list pane */}
            <div style={{
              width: 340, flexShrink: 0, borderRight: '1px solid var(--border)',
              display: 'flex', flexDirection: 'column', overflow: 'hidden',
            }}>
              <div style={{ padding: '10px 14px 8px', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
                <div style={{ fontSize: 15, fontWeight: 700 }}>Cases</div>
                <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>Found 1 out of 10,354 results</div>
              </div>
              <div style={{
                display: 'flex', alignItems: 'center', gap: 6,
                padding: '7px 10px', borderBottom: '1px solid var(--border)', flexShrink: 0,
              }}>
                <div style={{
                  fontSize: 11, color: 'var(--text-secondary)',
                  background: 'var(--bg-card)', border: '1px solid var(--border-light)',
                  borderRadius: 4, padding: '3px 10px', display: 'flex', alignItems: 'center', gap: 6,
                }}>
                  案例编号 = 5254
                  <span style={{ color: 'var(--text-muted)', marginLeft: 4, cursor: 'pointer' }}>✕</span>
                </div>
                <button
                  onClick={() => alert('Add OR filter condition')}
                  style={{
                    background: 'var(--bg-card)', border: '1px solid var(--border-light)',
                    color: 'var(--text-muted)', borderRadius: 4, padding: '2px 7px',
                    fontSize: 10.5, cursor: 'pointer',
                  }}>+OR</button>
                <button
                  onClick={() => setSelectedCase('INC5254')}
                  style={{
                    background: 'var(--bg-card)', border: '1px solid var(--border-light)',
                    color: 'var(--text-muted)', borderRadius: 4, padding: '2px 7px',
                    fontSize: 10.5, cursor: 'pointer',
                  }}>Revert</button>
              </div>
              <div style={{ flex: 1, overflowY: 'auto' }}>
                {CASES.map(c => (
                  <div
                    key={c.id}
                    onClick={() => setSelectedCase(c.id)}
                    style={{
                      padding: selectedCase === c.id ? '10px 14px 10px 12px' : '10px 14px',
                      borderBottom: '1px solid var(--border)',
                      borderLeft: selectedCase === c.id ? '2px solid var(--accent-orange)' : '2px solid transparent',
                      background: selectedCase === c.id ? 'rgba(250,88,45,.07)' : 'transparent',
                      cursor: 'pointer',
                      display: 'flex', flexDirection: 'column', gap: 4,
                      transition: 'background .12s',
                    }}
                  >
                    <div style={{ display: 'flex', alignItems: 'center', gap: 7 }}>
                      <span style={{ color: '#f9a825', fontSize: 12 }}>★</span>
                      <span style={{
                        fontSize: 9, fontWeight: 700, padding: '1px 6px', borderRadius: 3,
                        color: 'white', background: SEV_PILL_BG[c.severity],
                      }}>{c.severity}</span>
                      <span style={{ fontSize: 11, fontWeight: 700, color: 'var(--text-secondary)', minWidth: 20 }}>{c.score}</span>
                      {c.badge && (
                        <span style={{
                          fontSize: 9, color: 'var(--text-muted)',
                          border: '1px solid var(--border-light)',
                          padding: '1px 5px', borderRadius: 3,
                        }}>{c.badge}</span>
                      )}
                      <span style={{ fontSize: 12.5, fontWeight: 600, color: 'var(--text-primary)', flex: 1 }}>
                        {c.displayId} {c.name}
                      </span>
                    </div>
                    <div style={{
                      fontSize: 11, color: 'var(--text-muted)',
                      whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                    }}>{c.description}</div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 10, fontSize: 10.5, color: 'var(--text-muted)' }}>
                      <span>{c.issueLabel}</span>
                      {c.sources.length > 0 && (
                        <div style={{ display: 'flex', gap: 3 }}>
                          {c.sources.map((s, i) => (
                            <div key={i} style={{
                              width: 14, height: 14, borderRadius: 2,
                              background: 'var(--bg-card2)', display: 'flex',
                              alignItems: 'center', justifyContent: 'center',
                              fontSize: 8, color: 'var(--text-muted)',
                            }}>{s}</div>
                          ))}
                        </div>
                      )}
                      {c.extraMeta?.map((m, i) => <span key={i}>{m}</span>)}
                      <span>{c.status}</span>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {/* Right detail pane */}
            <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minWidth: 0 }}>

              {/* Detail header */}
              <div style={{ padding: '12px 18px 0', borderBottom: '1px solid var(--border)', flexShrink: 0 }}>
                {/* Title row */}
                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: 4 }}>
                  <span style={{ color: '#f9a825', fontSize: 14 }}>★</span>
                  <span style={{
                    fontSize: 10, fontWeight: 700, padding: '2px 8px', borderRadius: 3,
                    color: 'white', background: 'var(--high)',
                  }}>H</span>
                  <span style={{ fontSize: 13, fontWeight: 700, color: 'var(--text-secondary)', minWidth: 28 }}>41</span>
                  <span style={{
                    fontSize: 11, color: 'var(--text-muted)',
                    border: '1px solid var(--border-light)', padding: '2px 7px', borderRadius: 3,
                  }}>Security</span>
                  <span style={{ fontSize: 12, fontWeight: 700, color: 'var(--accent-orange)', fontFamily: 'monospace' }}>ID-5254</span>
                  <span style={{ fontSize: 16, fontWeight: 700 }}>Volume Shadow Deletion Attempt</span>
                  <span style={{ marginLeft: 'auto', display: 'flex', gap: 8, alignItems: 'center' }}>
                    <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                      Assigned: <span style={{ color: 'var(--accent-blue)', cursor: 'pointer' }}>Assign to me</span>
                    </span>
                    <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>
                      Status: <span style={{ color: 'var(--text-secondary)' }}>⊕ 处理中</span>
                    </span>
                    <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>开放 for a year</span>
                  </span>
                </div>

                {/* Description */}
                <div style={{
                  fontSize: 11, color: 'var(--text-muted)', marginBottom: 6,
                  whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis',
                }}>
                  'Volume Shadow Deletion Attempt - 1186929355' along with 16 other alerts generated by XSIAM Analytics BIOC, XSIAM Agent, PAN NGFW, Correlation, XSIAM Analytics...
                </div>

                {/* Meta row */}
                <div style={{
                  display: 'flex', alignItems: 'center', gap: 14,
                  fontSize: 11, color: 'var(--text-muted)', marginBottom: 8,
                }}>
                  <span style={{ color: 'var(--text-secondary)' }}>17 Issues</span>
                  <div style={{ display: 'flex', gap: 3 }}>
                    {(['A', '⊕', '▲', '⚡', '◎'] as const).map((s, i) => (
                      <div key={i} style={{
                        width: 14, height: 14, borderRadius: 2,
                        background: 'var(--bg-card2)', display: 'flex',
                        alignItems: 'center', justifyContent: 'center',
                        fontSize: 8, color: 'var(--text-muted)',
                      }}>{s}</div>
                    ))}
                  </div>
                  <span>👤 2</span>
                  <span>🖥 4</span>
                  <span>💬 2</span>
                  <button
                    onClick={() => setActiveTab('warroom')}
                    style={{
                      marginLeft: 'auto', fontSize: 11,
                      background: 'var(--bg-card)', border: '1px solid var(--border-light)',
                      color: 'var(--text-muted)', borderRadius: 4, padding: '4px 10px',
                      cursor: 'pointer',
                    }}>View MDR Thread</button>
                </div>

                {/* MITRE ATT&CK bar */}
                <div style={{
                  display: 'flex', gap: 0, overflowX: 'auto',
                  padding: '6px 0 10px',
                  scrollbarWidth: 'none',
                }}>
                  {MITRE_CELLS.map((cell, idx) => {
                    let countColor: string
                    if (cell.color) {
                      countColor = cell.color
                    } else if (cell.count === 0) {
                      countColor = 'var(--text-muted)'
                    } else {
                      countColor = 'var(--accent-blue)'
                    }
                    return (
                      <div key={idx} style={{
                        display: 'flex', flexDirection: 'column', alignItems: 'center',
                        minWidth: 90, padding: '0 6px',
                        borderRight: idx < MITRE_CELLS.length - 1 ? '1px solid var(--border)' : 'none',
                        gap: 2,
                      }}>
                        <div style={{ fontSize: 15, fontWeight: 700, color: countColor }}>{cell.count}</div>
                        <div style={{
                          fontSize: 9, color: 'var(--text-muted)',
                          textAlign: 'center', whiteSpace: 'pre-line',
                        }}>{cell.label}</div>
                      </div>
                    )
                  })}
                </div>
              </div>

              {/* Tab bar */}
              <div style={{
                display: 'flex', gap: 0, padding: '0 18px',
                borderBottom: '1px solid var(--border)',
                background: 'var(--bg-sidebar)', flexShrink: 0,
              }}>
                {[
                  { id: 'overview', label: 'Overview ✦' },
                  { id: 'assets', label: 'Key Assets & Artifacts' },
                  { id: 'alerts', label: 'Issues & Insights', badge: '17' },
                  { id: 'timeline', label: 'Timeline' },
                  { id: 'warroom', label: 'Case War Room' },
                  { id: 'executions', label: 'Executions' },
                ].map(tab => (
                  <div
                    key={tab.id}
                    onClick={() => setActiveTab(tab.id)}
                    style={{
                      padding: '9px 14px',
                      fontSize: 12.5,
                      color: activeTab === tab.id ? 'var(--text-primary)' : 'var(--text-muted)',
                      cursor: 'pointer',
                      borderBottom: activeTab === tab.id ? '2px solid var(--accent-orange)' : '2px solid transparent',
                      marginBottom: -1,
                      whiteSpace: 'nowrap',
                      display: 'flex', alignItems: 'center', gap: 5,
                      transition: 'color .12s',
                    }}
                  >
                    {tab.label}
                    {tab.badge && (
                      <span style={{
                        fontSize: 9, fontWeight: 700,
                        background: 'var(--accent-orange)', color: 'white',
                        padding: '1px 5px', borderRadius: 8,
                      }}>{tab.badge}</span>
                    )}
                  </div>
                ))}
              </div>

              {/* Tab content */}
              <div style={{ flex: 1, overflow: 'hidden', display: 'flex', flexDirection: 'column', minHeight: 0 }}>

                {/* ── Overview tab ── */}
                {activeTab === 'overview' && (
                  <div style={{
                    display: 'grid',
                    gridTemplateColumns: '200px 1fr 220px 220px',
                    gap: 12,
                    padding: '14px 18px',
                    overflowY: 'auto',
                    flex: 1,
                  }}>

                    {/* Issues panel */}
                    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 6, padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 8 }}>
                      <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.6px', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                        ISSUES
                        <span style={{ fontSize: 10, color: 'var(--accent-blue)', cursor: 'pointer' }}>See all ›</span>
                      </div>
                      <div style={{ fontSize: 36, fontWeight: 700, lineHeight: 1, color: 'var(--text-primary)' }}>17</div>
                      <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Total Issues</div>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                        {[
                          { label: 'High', pct: 40, val: 4, color: 'var(--high)' },
                          { label: 'Medium', pct: 50, val: 5, color: 'var(--medium)' },
                          { label: 'Low', pct: 80, val: 8, color: 'var(--accent-blue)' },
                        ].map(row => (
                          <div key={row.label} style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 11 }}>
                            <span style={{ width: 44, color: row.color }}>{row.label}</span>
                            <div style={{ flex: 1, height: 4, background: 'var(--border)', borderRadius: 2 }}>
                              <div style={{ width: `${row.pct}%`, height: 4, background: row.color, borderRadius: 2 }} />
                            </div>
                            <span style={{ width: 16, textAlign: 'right', color: 'var(--text-secondary)', fontSize: 11 }}>{row.val}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                    {/* Artifacts panel */}
                    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 6, padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 8 }}>
                      <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.6px', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                        ARTIFACTS (47)
                        <span style={{ fontSize: 10, color: 'var(--accent-blue)', cursor: 'pointer' }}>See all ›</span>
                      </div>
                      {ARTIFACTS.map((a, i) => (
                        <div key={i} style={{ display: 'flex', flexDirection: 'column', gap: 2, padding: '6px 0', borderBottom: i < ARTIFACTS.length - 1 ? '1px solid var(--border)' : 'none', fontSize: 11.5 }}>
                          <div style={{ color: 'var(--accent-blue)', cursor: 'pointer', fontFamily: 'monospace', fontSize: 11 }}>
                            {a.name} ({a.hash})
                          </div>
                          <div style={{ display: 'flex', gap: 5, alignItems: 'center', fontSize: 10, color: 'var(--text-muted)' }}>
                            {a.wf && <span>WF</span>}
                            <span style={{
                              padding: '1px 5px', borderRadius: 3,
                              border: `1px solid ${a.verdict === 'malware' ? '#e5393544' : '#00c89644'}`,
                              color: a.verdict === 'malware' ? '#e53935' : 'var(--accent-green)',
                            }}>
                              {a.verdict === 'malware' ? '🔴 Malware' : 'Benign'}
                            </span>
                            {a.vtScore && <span>| {a.vtScore}</span>}
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Assets panel */}
                    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 6, padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 8 }}>
                      <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.6px', color: 'var(--text-muted)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                        ASSETS (3)
                        <span style={{ fontSize: 10, color: 'var(--accent-blue)', cursor: 'pointer' }}>See all ›</span>
                      </div>
                      {ASSETS.map((a, i) => (
                        <div key={i} style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '6px 0', borderBottom: i < ASSETS.length - 1 ? '1px solid var(--border)' : 'none', fontSize: 11.5 }}>
                          <span style={{ fontSize: 13, color: 'var(--text-muted)' }}>{a.icon}</span>
                          <div style={{ display: 'flex', flexDirection: 'column', flex: 1, gap: 2 }}>
                            <span style={{ color: 'var(--text-primary)', fontFamily: 'monospace', fontSize: 11 }}>{a.name}</span>
                            <div style={{ display: 'flex', gap: 4, alignItems: 'center' }}>
                              <span style={{
                                fontSize: 9, fontWeight: 700, padding: '1px 5px', borderRadius: 3,
                                color: 'white', background: a.tag === 'EG' ? '#6d28d9' : '#dc2626',
                              }}>{a.tag}</span>
                              {a.badges.map((b, bi) => (
                                <span key={bi} style={{
                                  fontSize: 9.5, color: 'var(--text-muted)',
                                  border: '1px solid var(--border-light)', padding: '1px 5px', borderRadius: 3,
                                  cursor: 'pointer',
                                }}>{b}</span>
                              ))}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>

                    {/* Automation panel */}
                    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 6, padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 8 }}>
                      <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.6px', color: 'var(--text-muted)' }}>
                        AUTOMATION
                      </div>
                      <div style={{ display: 'flex', alignItems: 'flex-start', gap: 8, fontSize: 11.5, padding: '4px 0' }}>
                        <span style={{ color: 'var(--accent-green)', fontSize: 13, flexShrink: 0 }}>✓</span>
                        <div>
                          <div style={{ color: 'var(--text-secondary)' }}>
                            <b style={{ color: 'var(--accent-green)' }}>1</b> Playbook complete
                          </div>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 5, marginTop: 4 }}>
                            <span style={{
                              fontSize: 11, color: 'var(--text-muted)',
                              background: 'var(--bg-card2)', border: '1px solid var(--border-light)',
                              padding: '1px 5px', borderRadius: 3,
                            }}>M</span>
                            <span style={{ fontSize: 10.5, color: 'var(--accent-blue)', cursor: 'pointer' }}>218359 - WildFire Malware</span>
                          </div>
                          <div style={{ fontSize: 10.5, color: 'var(--accent-blue)', cursor: 'pointer', marginTop: 4 }}>
                            View in Issues &amp; Insights tab
                          </div>
                        </div>
                      </div>
                    </div>

                    {/* Issue Sources panel */}
                    <div style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 6, padding: '12px 14px', display: 'flex', flexDirection: 'column', gap: 8, gridColumn: 1 }}>
                      <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '.6px', color: 'var(--text-muted)' }}>
                        ISSUE SOURCES (6)
                      </div>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 5, fontSize: 11.5 }}>
                        {ISSUE_SOURCES.map((s, i) => (
                          <div key={i} style={{ display: 'flex', justifyContent: 'space-between' }}>
                            <span style={{ color: 'var(--text-muted)' }}>{s.label}</span>
                            <span style={{ color: 'var(--text-primary)', fontWeight: 600 }}>{s.count}</span>
                          </div>
                        ))}
                      </div>
                    </div>

                  </div>
                )}

                {/* ── Issues & Insights tab ── */}
                {activeTab === 'alerts' && (
                  <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
                    {/* Sub-tab bar */}
                    <div style={{
                      display: 'flex', alignItems: 'center', gap: 2,
                      padding: '8px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0,
                    }}>
                      {(['alerts', 'insights'] as const).map(sub => (
                        <button
                          key={sub}
                          onClick={() => setAlertSubTab(sub)}
                          style={{
                            padding: '4px 14px', fontSize: 12, borderRadius: 4,
                            cursor: 'pointer', transition: 'all .12s',
                            color: alertSubTab === sub ? 'var(--text-primary)' : 'var(--text-muted)',
                            background: alertSubTab === sub ? 'rgba(255,255,255,.08)' : 'none',
                            border: 'none',
                          }}
                        >
                          {sub === 'alerts' ? '73 Alerts' : '212 Insights'}
                          <span style={{
                            fontSize: 10, fontWeight: 700, marginLeft: 4,
                            color: alertSubTab === sub ? 'var(--accent-orange)' : 'var(--text-muted)',
                          }}>{sub === 'alerts' ? '73' : '212'}</span>
                        </button>
                      ))}
                      <span style={{ fontSize: 11, color: 'var(--text-muted)', marginLeft: 10 }}>
                        Alerts in this Incident &nbsp; Found {alertSubTab === 'alerts' ? 73 : 212} results
                      </span>
                    </div>
                    {/* Alerts table */}
                    <div style={{ flex: 1, overflowY: 'auto' }}>
                      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11.5 }}>
                        <thead>
                          <tr>
                            <th style={thStyle}></th>
                            <th style={thStyle}></th>
                            <th style={{ ...thStyle, width: 72 }}>Severity ↕</th>
                            <th style={thStyle}>Alert Source ↕</th>
                            <th style={thStyle}>Action ↕</th>
                            <th style={thStyle}>Category ↕</th>
                            <th style={thStyle}>Alert Name ↕</th>
                            <th style={thStyle}>Description ↕</th>
                          </tr>
                        </thead>
                        <tbody>
                          {ALERTS.map((row, i) => (
                            <tr key={i} style={{ cursor: 'default' }}>
                              <td style={tdStyle}>
                                <span style={{ width: 7, height: 7, borderRadius: '50%', background: 'var(--accent-green)', display: 'inline-block' }} />
                              </td>
                              <td style={tdStyle}></td>
                              <td style={tdStyle}>
                                <span style={{
                                  display: 'inline-block', fontSize: 9, fontWeight: 700,
                                  padding: '2px 7px', borderRadius: 3, color: 'white',
                                  background: SEV_TAG_BG[row.sev],
                                  whiteSpace: 'nowrap',
                                }}>{row.sev}</span>
                              </td>
                              <td style={{ ...tdStyle, whiteSpace: 'nowrap', fontSize: 11 }}>{row.source}</td>
                              <td style={tdStyle}>
                                <div style={{ display: 'flex', alignItems: 'center', whiteSpace: 'nowrap' }}>
                                  <span style={{
                                    width: 7, height: 7, borderRadius: '50%',
                                    display: 'inline-block', marginRight: 4,
                                    background: getActionDotColor(row.action),
                                    flexShrink: 0, verticalAlign: 'middle',
                                  }} />
                                  {row.action}
                                </div>
                              </td>
                              <td style={{ ...tdStyle, whiteSpace: 'nowrap' }}>{row.category}</td>
                              <td style={{ ...tdStyle, color: 'var(--text-primary)', maxWidth: 260 }}>
                                {row.starred && <span style={{ color: '#f9a825', marginRight: 4 }}>★</span>}
                                {row.name}
                              </td>
                              <td style={{
                                ...tdStyle,
                                color: 'var(--text-muted)', fontSize: 11,
                                maxWidth: 180, overflow: 'hidden',
                                textOverflow: 'ellipsis', whiteSpace: 'nowrap',
                              }}>{row.description}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                )}

                {/* ── Key Assets & Artifacts tab ── */}
                {activeTab === 'assets' && (
                  <div style={{ flex: 1, display: 'flex', overflow: 'hidden', minHeight: 0 }}>
                    {/* Left: Artifacts */}
                    <div style={{ flex: 1, display: 'flex', flexDirection: 'column', borderRight: '1px solid var(--border)', overflow: 'hidden' }}>
                      <div style={{ padding: '10px 18px', borderBottom: '1px solid var(--border)', fontSize: 10, fontWeight: 700, letterSpacing: '.6px', color: 'var(--text-muted)', textTransform: 'uppercase', flexShrink: 0 }}>
                        ARTIFACTS ({ALL_ARTIFACTS.length})
                      </div>
                      <div style={{ flex: 1, overflowY: 'auto' }}>
                        <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11.5 }}>
                          <thead>
                            <tr>
                              <th style={thStyle}>File Name</th>
                              <th style={thStyle}>SHA256</th>
                              <th style={thStyle}>WF</th>
                              <th style={thStyle}>Verdict</th>
                              <th style={thStyle}>VT Score</th>
                            </tr>
                          </thead>
                          <tbody>
                            {ALL_ARTIFACTS.map((a, i) => (
                              <tr key={i} style={{ cursor: 'default' }}>
                                <td style={{ ...tdStyle, fontFamily: 'monospace', color: 'var(--accent-blue)', maxWidth: 180 }}>{a.name}</td>
                                <td style={{ ...tdStyle, fontFamily: 'monospace', color: 'var(--text-muted)', fontSize: 10.5 }}>{a.hash}</td>
                                <td style={tdStyle}>{a.wf ? <span style={{ color: 'var(--accent-blue)', fontSize: 10 }}>WF</span> : '—'}</td>
                                <td style={tdStyle}>
                                  <span style={{
                                    fontSize: 10, padding: '2px 6px', borderRadius: 3,
                                    border: `1px solid ${a.verdict === 'malware' ? '#e5393544' : '#00c89644'}`,
                                    color: a.verdict === 'malware' ? '#e53935' : 'var(--accent-green)',
                                  }}>
                                    {a.verdict === 'malware' ? '🔴 Malware' : '✓ Benign'}
                                  </span>
                                </td>
                                <td style={{ ...tdStyle, color: a.vtScore ? (parseInt(a.vtScore.replace('VT', '')) > 0 ? '#e53935' : 'var(--text-muted)') : 'var(--text-muted)', fontSize: 11 }}>{a.vtScore ?? '—'}</td>
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    </div>
                    {/* Right: Assets */}
                    <div style={{ width: 280, flexShrink: 0, display: 'flex', flexDirection: 'column', overflow: 'hidden' }}>
                      <div style={{ padding: '10px 18px', borderBottom: '1px solid var(--border)', fontSize: 10, fontWeight: 700, letterSpacing: '.6px', color: 'var(--text-muted)', textTransform: 'uppercase', flexShrink: 0 }}>
                        ASSETS ({ALL_ASSETS.length})
                      </div>
                      <div style={{ flex: 1, overflowY: 'auto', padding: '8px 14px', display: 'flex', flexDirection: 'column', gap: 6 }}>
                        {ALL_ASSETS.map((a, i) => (
                          <div key={i} style={{
                            background: 'var(--bg-card)', border: '1px solid var(--border)',
                            borderRadius: 6, padding: '10px 12px',
                            display: 'flex', alignItems: 'flex-start', gap: 10,
                          }}>
                            <span style={{ fontSize: 16, flexShrink: 0 }}>{a.icon}</span>
                            <div style={{ flex: 1, minWidth: 0 }}>
                              <div style={{ fontFamily: 'monospace', fontSize: 11.5, color: 'var(--text-primary)', marginBottom: 4 }}>{a.name}</div>
                              <div style={{ display: 'flex', flexWrap: 'wrap', gap: 4, alignItems: 'center' }}>
                                <span style={{ fontSize: 9, fontWeight: 700, padding: '1px 5px', borderRadius: 3, color: 'white', background: a.tag === 'EG' ? '#6d28d9' : '#dc2626' }}>{a.tag}</span>
                                {a.badges.map((b, bi) => (
                                  <span key={bi} style={{ fontSize: 9.5, color: 'var(--text-muted)', border: '1px solid var(--border-light)', padding: '1px 5px', borderRadius: 3 }}>{b}</span>
                                ))}
                              </div>
                            </div>
                          </div>
                        ))}
                      </div>
                    </div>
                  </div>
                )}

                {/* ── Timeline tab ── */}
                {activeTab === 'timeline' && (
                  <div style={{ flex: 1, overflowY: 'auto', padding: '18px 28px' }}>
                    <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 14 }}>
                      {TIMELINE_EVENTS.length} events · Incident INC-5254 · Volume Shadow Deletion Attempt
                    </div>
                    <div style={{ position: 'relative', paddingLeft: 28 }}>
                      {/* vertical spine */}
                      <div style={{ position: 'absolute', left: 8, top: 0, bottom: 0, width: 2, background: 'var(--border)' }} />
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 0 }}>
                        {TIMELINE_EVENTS.map((ev, i) => {
                          const dotColor = ev.type === 'alert' ? '#e53935' : ev.type === 'action' ? 'var(--accent-orange)' : ev.type === 'note' ? 'var(--accent-blue)' : ev.type === 'status' ? 'var(--accent-green)' : '#8a8fa0'
                          const icon = ev.type === 'alert' ? '⚠' : ev.type === 'action' ? '⚡' : ev.type === 'note' ? '📝' : ev.type === 'status' ? '↕' : '👤'
                          return (
                            <div key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 14, paddingBottom: 18, position: 'relative' }}>
                              {/* dot */}
                              <div style={{
                                position: 'absolute', left: -20, top: 2,
                                width: 16, height: 16, borderRadius: '50%',
                                background: dotColor, display: 'flex', alignItems: 'center', justifyContent: 'center',
                                fontSize: 8, color: 'white', flexShrink: 0, zIndex: 1,
                                border: '2px solid var(--bg-primary)',
                              }}>{icon}</div>
                              <div style={{ flex: 1, background: 'var(--bg-card)', border: '1px solid var(--border)', borderRadius: 6, padding: '8px 12px' }}>
                                <div style={{ display: 'flex', alignItems: 'center', gap: 8, marginBottom: ev.detail || ev.actor ? 4 : 0 }}>
                                  <span style={{ fontSize: 10, color: 'var(--text-muted)', fontFamily: 'monospace', flexShrink: 0 }}>{ev.time}</span>
                                  {ev.actor && <span style={{ fontSize: 10, color: 'var(--accent-blue)', flexShrink: 0 }}>{ev.actor}</span>}
                                  <span style={{ fontSize: 12, color: 'var(--text-primary)' }}>{ev.text}</span>
                                </div>
                                {ev.detail && (
                                  <div style={{ fontSize: 11, color: 'var(--text-muted)', fontFamily: 'monospace', marginTop: 2 }}>{ev.detail}</div>
                                )}
                              </div>
                            </div>
                          )
                        })}
                      </div>
                    </div>
                  </div>
                )}

                {/* ── Case War Room tab ── */}
                {activeTab === 'warroom' && (
                  <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 }}>
                    {/* Header */}
                    <div style={{
                      padding: '8px 18px', borderBottom: '1px solid var(--border)', flexShrink: 0,
                      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                    }}>
                      <div>
                        <span style={{ fontSize: 12, fontWeight: 600 }}>INC-5254 War Room</span>
                        <span style={{ fontSize: 11, color: 'var(--text-muted)', marginLeft: 10 }}>3 members active</span>
                      </div>
                      <div style={{ display: 'flex', gap: 8 }}>
                        {['watson', 'ir-team', 'Automation'].map(m => (
                          <span key={m} style={{
                            fontSize: 10, padding: '2px 8px', borderRadius: 10,
                            background: 'var(--bg-card)', border: '1px solid var(--border-light)',
                            color: 'var(--text-secondary)',
                          }}>● {m}</span>
                        ))}
                      </div>
                    </div>
                    {/* Message thread */}
                    <div ref={warRoomRef} style={{ flex: 1, overflowY: 'auto', padding: '14px 18px', display: 'flex', flexDirection: 'column', gap: 10 }}>
                      {warRoomMsgs.map(msg => (
                        <div key={msg.id} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
                          <div style={{
                            width: 28, height: 28, borderRadius: '50%', flexShrink: 0,
                            background: msg.author === 'Automation' || msg.author === 'System' || msg.author === 'AutoAssign' ? 'var(--accent-orange)' : msg.author === 'watson' ? '#6d28d9' : msg.author === 'ir-team' ? '#0891b2' : '#374151',
                            display: 'flex', alignItems: 'center', justifyContent: 'center',
                            fontSize: 11, fontWeight: 700, color: 'white',
                          }}>{msg.avatar}</div>
                          <div style={{ flex: 1, minWidth: 0 }}>
                            <div style={{ display: 'flex', alignItems: 'baseline', gap: 8, marginBottom: 3 }}>
                              <span style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-primary)' }}>{msg.author}</span>
                              <span style={{ fontSize: 10, color: 'var(--text-muted)' }}>{msg.time}</span>
                            </div>
                            <div style={{
                              background: 'var(--bg-card)', border: '1px solid var(--border)',
                              borderRadius: 6, padding: '8px 12px', fontSize: 12,
                              color: 'var(--text-secondary)', lineHeight: 1.5,
                            }}>
                              {msg.text}
                              {msg.attachments && msg.attachments.length > 0 && (
                                <div style={{ marginTop: 6, display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                                  {msg.attachments.map((a, ai) => (
                                    <span key={ai} style={{
                                      fontSize: 10, color: 'var(--accent-blue)', border: '1px solid var(--border-light)',
                                      padding: '2px 8px', borderRadius: 3, cursor: 'pointer',
                                    }}>📎 {a}</span>
                                  ))}
                                </div>
                              )}
                            </div>
                          </div>
                        </div>
                      ))}
                    </div>
                    {/* Input */}
                    <div style={{
                      padding: '10px 18px', borderTop: '1px solid var(--border)',
                      flexShrink: 0, display: 'flex', gap: 8, alignItems: 'center',
                    }}>
                      <input
                        className="filter-input"
                        style={{ flex: 1 }}
                        placeholder="Message the war room…"
                        value={warRoomInput}
                        onChange={e => setWarRoomInput(e.target.value)}
                        onKeyDown={e => {
                          if (e.key === 'Enter' && warRoomInput.trim()) {
                            setWarRoomMsgs(prev => [...prev, {
                              id: Date.now(), author: 'watson', avatar: 'W',
                              time: new Date().toLocaleTimeString('en', { hour: '2-digit', minute: '2-digit', hour12: false }),
                              text: warRoomInput.trim(),
                            }])
                            setWarRoomInput('')
                            setTimeout(() => { if (warRoomRef.current) warRoomRef.current.scrollTop = warRoomRef.current.scrollHeight }, 50)
                          }
                        }}
                      />
                      <button
                        onClick={() => {
                          if (!warRoomInput.trim()) return
                          setWarRoomMsgs(prev => [...prev, {
                            id: Date.now(), author: 'watson', avatar: 'W',
                            time: new Date().toLocaleTimeString('en', { hour: '2-digit', minute: '2-digit', hour12: false }),
                            text: warRoomInput.trim(),
                          }])
                          setWarRoomInput('')
                          setTimeout(() => { if (warRoomRef.current) warRoomRef.current.scrollTop = warRoomRef.current.scrollHeight }, 50)
                        }}
                        style={{
                          background: 'var(--accent-orange)', border: 'none', color: 'white',
                          borderRadius: 4, padding: '5px 14px', fontSize: 12, cursor: 'pointer',
                        }}>Send</button>
                    </div>
                  </div>
                )}

                {/* ── Executions tab ── */}
                {activeTab === 'executions' && (
                  <div style={{ flex: 1, display: 'flex', flexDirection: 'column', overflow: 'hidden', minHeight: 0 }}>
                    <div style={{ padding: '8px 18px 8px', borderBottom: '1px solid var(--border)', flexShrink: 0, display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                      <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{EXECUTIONS.length} playbook executions in this incident</span>
                      <div style={{ display: 'flex', gap: 6 }}>
                        {['All', 'Completed', 'Running', 'Failed'].map(f => (
                          <span key={f} style={{
                            fontSize: 10.5, padding: '2px 8px', borderRadius: 3,
                            background: f === 'All' ? 'rgba(255,255,255,.08)' : 'none',
                            color: f === 'All' ? 'var(--text-primary)' : 'var(--text-muted)',
                            border: '1px solid var(--border-light)', cursor: 'pointer',
                          }}>{f}</span>
                        ))}
                      </div>
                    </div>
                    <div style={{ flex: 1, overflowY: 'auto' }}>
                      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 11.5 }}>
                        <thead>
                          <tr>
                            <th style={thStyle}>Execution ID</th>
                            <th style={thStyle}>Playbook</th>
                            <th style={thStyle}>Trigger</th>
                            <th style={thStyle}>状态</th>
                            <th style={thStyle}>Started At</th>
                            <th style={thStyle}>Duration</th>
                            <th style={thStyle}>Actor</th>
                            <th style={thStyle}>Steps</th>
                          </tr>
                        </thead>
                        <tbody>
                          {EXECUTIONS.map((ex, i) => {
                            const statusColor = ex.status === 'completed' ? 'var(--accent-green)' : ex.status === 'running' ? 'var(--accent-orange)' : '#e53935'
                            const statusLabel = ex.status === 'completed' ? '✓ Completed' : ex.status === 'running' ? '⟳ Running' : '✕ Failed'
                            return (
                              <tr key={i} style={{ cursor: 'default' }}>
                                <td style={{ ...tdStyle, fontFamily: 'monospace', color: 'var(--accent-blue)', fontSize: 11 }}>{ex.id}</td>
                                <td style={{ ...tdStyle, maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{ex.playbook}</td>
                                <td style={{ ...tdStyle, color: 'var(--text-muted)', fontSize: 11 }}>{ex.trigger}</td>
                                <td style={tdStyle}>
                                  <span style={{ fontSize: 10.5, color: statusColor }}>{statusLabel}</span>
                                </td>
                                <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 11, color: 'var(--text-muted)' }}>{ex.startedAt}</td>
                                <td style={{ ...tdStyle, fontFamily: 'monospace', fontSize: 11 }}>{ex.duration}</td>
                                <td style={{ ...tdStyle, color: 'var(--text-secondary)' }}>{ex.actor}</td>
                                <td style={tdStyle}>
                                  <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                                    <div style={{ width: 50, height: 4, background: 'var(--border)', borderRadius: 2 }}>
                                      <div style={{
                                        width: `${(ex.stepsOk / ex.steps) * 100}%`, height: 4,
                                        background: ex.status === 'failed' ? '#e53935' : 'var(--accent-green)', borderRadius: 2,
                                      }} />
                                    </div>
                                    <span style={{ fontSize: 10.5, color: 'var(--text-muted)' }}>{ex.stepsOk}/{ex.steps}</span>
                                  </div>
                                </td>
                              </tr>
                            )
                          })}
                        </tbody>
                      </table>
                    </div>
                  </div>
                )}

              </div>
            </div>
          </div>
        </>
      )}

      {/* ── Policy Management View ── */}
      {mainView === 'policy' && (
        <>
          <PageHeader
            title="策略管理"
            subtitle="Prevention Policy Rules"
            actions={<>
              <span style={{
                fontSize: 10.5, color: '#8a8fa0',
                border: '1px solid var(--border-light)',
                padding: '2px 8px', borderRadius: 3,
              }}>Managed by Unit42 Managed Services</span>
              <button className="btn-secondary" style={{ fontSize: 12 }} onClick={() => setMainView('cases')}>← Cases</button>
            </>}
          />

          {/* Policy title bar */}
          <div style={{
            display: 'flex', alignItems: 'center', justifyContent: 'space-between',
            padding: '10px 18px', borderBottom: '1px solid var(--border)',
            flexShrink: 0, background: 'var(--bg-sidebar)',
          }}>
            <div>
              <div style={{ fontSize: 16, fontWeight: 700 }}>Prevention Policy Rules</div>
              <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Found 33 results</div>
            </div>
            <button
              onClick={() => alert('26 policies have elevated risk configurations. Review recommended.')}
              style={{
                display: 'flex', alignItems: 'center', gap: 6,
                background: '#2a1a00', border: '1px solid #ff9900aa',
                color: '#ff9900', borderRadius: 4, padding: '4px 12px',
                fontSize: 11.5, cursor: 'pointer',
              }}>⚠ View Risks associated with 26 policies</button>
          </div>

          {/* Policy context bar */}
          <div style={{
            padding: '10px 18px', borderBottom: '1px solid var(--border)',
            fontSize: 13, fontWeight: 600, flexShrink: 0,
          }}>
            Policy Details - Windows Default
          </div>

          {/* Split pane */}
          <div style={{ display: 'flex', flex: 1, overflow: 'hidden', minHeight: 0 }}>

            {/* Left: policy tree */}
            <div style={{
              width: 300, flexShrink: 0, borderRight: '1px solid var(--border)',
              overflowY: 'auto', padding: '10px 0',
            }}>
              {policyGroups.map(group => (
                <div key={group.id} style={{ marginBottom: 4 }}>
                  <div
                    onClick={() => togglePolicyGroup(group.id)}
                    style={{
                      display: 'flex', alignItems: 'center', gap: 7,
                      padding: '6px 14px',
                      fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)',
                      cursor: 'pointer',
                    }}
                  >
                    <span style={{ color: 'var(--text-muted)', fontSize: 10 }}>
                      {group.expanded ? '▼' : '▶'}
                    </span>
                    <span>{group.icon} {group.label}</span>
                    <span style={{ marginLeft: 'auto', fontSize: 11, color: 'var(--accent-blue)' }}>View</span>
                  </div>
                  {group.expanded && group.items.map((item, idx) => (
                    <div
                      key={idx}
                      onClick={() => setSelectedPolicy(item)}
                      style={{
                        padding: '5px 14px 5px 36px',
                        fontSize: 11.5,
                        color: selectedPolicy === item ? 'var(--text-primary)' : 'var(--text-muted)',
                        fontWeight: selectedPolicy === item ? 600 : 400,
                        cursor: 'pointer',
                        transition: 'all .12s',
                        background: selectedPolicy === item ? 'rgba(255,255,255,.04)' : 'transparent',
                      }}
                    >
                      {item}
                    </div>
                  ))}
                </div>
              ))}
            </div>

            {/* Right: policy detail */}
            <div style={{ flex: 1, overflowY: 'auto', padding: '18px 24px' }}>
              <div style={{ fontSize: 15, fontWeight: 700, marginBottom: 4 }}>{selectedPolicy}</div>
              <div style={{ fontSize: 12, color: 'var(--text-muted)', marginBottom: 18 }}>Windows Default</div>

              {/* Policy fields */}
              {[
                { label: 'Action Mode', default: 'Block' },
                { label: 'Quarantine Malicious Executables', default: 'Disabled' },
                { label: 'Action when file is unknown to WildFire', default: 'Run Local Analysis' },
                { label: 'Action when WildFire verdict is Benign Low Confidence', default: 'Run Local Analysis' },
              ].map((field, i) => (
                <div key={i} style={{ marginBottom: 16 }}>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '.4px' }}>
                    {field.label}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                    <div style={{
                      flex: 1, background: 'var(--bg-card2)', border: '1px solid var(--border-light)',
                      borderRadius: 4, padding: '6px 10px',
                      color: 'var(--text-muted)', fontSize: 12,
                      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                      cursor: 'pointer',
                    }}>
                      Select <span style={{ fontSize: 10, color: 'var(--text-muted)' }}>▾</span>
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 7, fontSize: 12, color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>
                      <div style={{
                        width: 14, height: 14, border: '1px solid var(--border-light)',
                        borderRadius: 2, background: 'var(--bg-card2)', flexShrink: 0,
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                        fontSize: 9, color: 'var(--accent-blue)',
                      }}>✓</div>
                      Use Default ({field.default})
                    </div>
                  </div>
                </div>
              ))}

              {/* Policy note */}
              <div style={{
                fontSize: 11, color: 'var(--text-muted)', fontStyle: 'italic',
                padding: '10px 14px', border: '1px solid var(--border)', borderRadius: 4,
                background: 'var(--bg-card)', lineHeight: 1.6, marginBottom: 14,
              }}>
                * Action on WildFire Benign LC verdict is supported from agent version 7.5 and above.
                <br />
                For agent version 7.4.x action on Benign LC verdict is the same as the action for files with Unknown verdict.
                <br />
                To enable this capability, ensure that WildFire analysis scoring is enabled in your{' '}
                <span style={{ color: 'var(--accent-blue)', cursor: 'pointer' }}>Global Agent Settings</span>.
              </div>

              {/* More fields */}
              {[
                { label: 'Upload unknown files to WildFire', default: 'Enabled' },
                { label: 'Treat Grayware As Malware', default: 'Disabled' },
              ].map((field, i) => (
                <div key={i} style={{ marginBottom: 16 }}>
                  <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 6, textTransform: 'uppercase', letterSpacing: '.4px' }}>
                    {field.label}
                  </div>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
                    <div style={{
                      flex: 1, background: 'var(--bg-card2)', border: '1px solid var(--border-light)',
                      borderRadius: 4, padding: '6px 10px',
                      color: 'var(--text-muted)', fontSize: 12,
                      display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                      cursor: 'pointer',
                    }}>
                      Select <span style={{ fontSize: 10, color: 'var(--text-muted)' }}>▾</span>
                    </div>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 7, fontSize: 12, color: 'var(--text-secondary)', whiteSpace: 'nowrap' }}>
                      <div style={{
                        width: 14, height: 14, border: '1px solid var(--border-light)',
                        borderRadius: 2, background: 'var(--bg-card2)', flexShrink: 0,
                        display: 'flex', alignItems: 'center', justifyContent: 'center',
                        fontSize: 9, color: 'var(--accent-blue)',
                      }}>✓</div>
                      Use Default ({field.default})
                    </div>
                  </div>
                </div>
              ))}

              {/* Allowlist sections */}
              {['FILES / FOLDERS IN ALLOW LIST (0)', 'ALLOW LIST SIGNERS (0)'].map((title, i) => (
                <div key={i} style={{ border: '1px solid var(--border)', borderRadius: 4, overflow: 'hidden', marginBottom: 10 }}>
                  <div style={{
                    display: 'flex', alignItems: 'center', gap: 6,
                    padding: '7px 12px', background: 'var(--bg-card)',
                    fontSize: 11, fontWeight: 600, letterSpacing: '.4px', color: 'var(--text-muted)',
                    cursor: 'pointer',
                  }}>▶ {title}</div>
                </div>
              ))}

              <div style={{
                fontSize: 11, color: 'var(--text-muted)', fontStyle: 'italic',
                padding: '10px 14px', border: '1px solid var(--border)', borderRadius: 4,
                background: 'var(--bg-card)', lineHeight: 1.6, marginBottom: 14,
              }}>
                ⓘ The Allow Lists have been moved from the profile, and cannot be defined on this page.
                <br />
                <span style={{ color: 'var(--accent-blue)', cursor: 'pointer' }}>
                  Define new Allow Lists using the new "Legacy Agent Exceptions" page
                </span>
              </div>
            </div>

          </div>
        </>
      )}

      {/* ── Agentix AI Panel ── */}
      {agentix开放 && (
        <>
          {/* Overlay */}
          <div
            onClick={() => setAgentix开放(false)}
            style={{
              position: 'fixed', inset: 0,
              background: 'rgba(0,0,0,.55)', zIndex: 700,
            }}
          />
          {/* Panel */}
          <div style={{
            position: 'fixed', top: 0, bottom: 0, left: '50%', right: 0,
            background: 'var(--bg-card)',
            borderLeft: '1px solid #1a2535',
            zIndex: 800,
            display: 'flex', flexDirection: 'column',
            overflow: 'hidden',
          }}>
            {/* Panel header */}
            <div style={{
              display: 'flex', alignItems: 'center', justifyContent: 'space-between',
              padding: '10px 16px',
              borderBottom: '1px solid #1a2535',
              flexShrink: 0,
            }}>
              <span style={{ fontSize: 12, color: 'var(--text-muted)' }}>Endpoint Investigation Agent</span>
              <button
                onClick={() => setAgentix开放(false)}
                style={{
                  background: 'none', border: 'none', color: 'var(--text-muted)',
                  cursor: 'pointer', fontSize: 18, padding: '2px 6px', borderRadius: 4,
                }}>✕</button>
            </div>

            {/* Panel body */}
            <div
              ref={agentixBodyRef}
              style={{ flex: 1, overflowY: 'auto', padding: '24px 20px', display: 'flex', flexDirection: 'column', gap: 16 }}
            >
              {agentixSteps.map((step, i) => {
                if (step.type === 'greeting') {
                  return (
                    <div key={i} style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 12, padding: '30px 0 10px' }}>
                      <AgentixSpinner />
                      <div style={{ fontSize: 18, fontWeight: 400, color: 'var(--text-primary)', textAlign: 'center' }}>
                        Hello &mdash; Ready to assist with ID-5254.
                      </div>
                    </div>
                  )
                }
                if (step.type === 'userMsg') {
                  const fileHash = '9a55f55886285eef7ffabdd55c0232d1458175b1d868c03d3e304ce7d98980bc'
                  return (
                    <div key={i} style={{
                      background: 'var(--bg-card2)', border: '1px solid var(--border-light)',
                      borderRadius: 8, padding: '12px 14px',
                      fontSize: 12.5, color: 'var(--text-secondary)',
                    }}>
                      {step.text.toLowerCase().includes('block') ? (
                        <>Block this file<br /><code style={{ fontFamily: 'monospace', fontSize: 11, color: 'var(--accent-blue)', wordBreak: 'break-all' }}>{fileHash}</code></>
                      ) : step.text}
                    </div>
                  )
                }
                if (step.type === 'hashResult') {
                  const h = step.hash
                  return (
                    <div key={i}>
                      <div style={{ fontSize: 11, color: 'var(--text-muted)', marginBottom: 4 }}>
                        Results for: Hash {h.slice(0, 8)}...{h.slice(-4)}
                        <span style={{ marginLeft: 6, cursor: 'pointer', color: 'var(--text-muted)' }}>✕</span>
                      </div>
                      <div style={{
                        background: 'var(--bg-card)', border: '1px solid var(--border-light)',
                        borderRadius: 6, padding: '10px 12px', fontSize: 12, marginBottom: 8,
                      }}>
                        <span style={{ color: 'var(--accent-blue)' }}>{h.slice(0, 8)}...{h.slice(-4)}</span> is a SHA256 identified as{' '}
                        <span style={{ color: '#e53935', fontWeight: 600 }}>Malware</span> by WildFire
                      </div>
                    </div>
                  )
                }
                if (step.type === 'plan') {
                  const h = step.hash
                  return (
                    <div key={i} style={{ display: 'flex', flexDirection: 'column', gap: 10 }}>
                      <div style={{ fontSize: 12, fontWeight: 600, color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: 6 }}>
                        ▼ Plan
                      </div>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 3, fontSize: 12, paddingLeft: 14 }}>
                        <b style={{ color: 'var(--text-secondary)' }}>Interpreted User Input:</b>
                        <span style={{ color: 'var(--text-muted)', fontSize: 11 }}>Block the file hash {h.slice(0, 8)}...{h.slice(-4)}.</span>
                      </div>
                      <div style={{ display: 'flex', flexDirection: 'column', gap: 3, fontSize: 12, paddingLeft: 14 }}>
                        <b style={{ color: 'var(--text-secondary)' }}>Planned Steps to Address Your Request:</b>
                        <span style={{ color: 'var(--text-muted)', fontSize: 11 }}>
                          1. Will execute{' '}
                          <code style={{ fontFamily: 'monospace', fontSize: 11, color: 'var(--accent-blue)' }}>CortexBlockFile</code>{' '}
                          to block the provided file hash.
                        </span>
                        <span style={{ color: 'var(--text-muted)', fontSize: 11 }}>• Blocking the file hash using CortexBlockFile action.</span>
                      </div>
                    </div>
                  )
                }
                if (step.type === 'approval') {
                  return (
                    <div key={i} style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                      <div style={{ fontSize: 12, color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: 6 }}>
                        <StepSpinner /> Endpoint Investigation
                      </div>
                      <div style={{
                        display: 'flex', alignItems: 'flex-start', gap: 8,
                        background: '#2a1a00', border: '1px solid #ff9900aa',
                        borderRadius: 6, padding: '10px 12px',
                        fontSize: 12, color: '#ff9900',
                      }}>
                        ⚠ <span>Sensitive action detected — User approval required</span>
                      </div>
                      <div style={{ fontSize: 12, color: 'var(--text-muted)', paddingLeft: 14 }}>
                        Blocking the file hash using CortexBlockFile action.
                      </div>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 10, paddingLeft: 14 }}>
                        <span style={{ fontSize: 12, color: 'var(--text-secondary)', flex: 1 }}>Should I proceed?</span>
                        <button
                          onClick={agentixApprove}
                          style={{
                            background: 'white', color: 'var(--bg-primary)',
                            border: 'none', borderRadius: 4, padding: '5px 18px',
                            fontSize: 12, fontWeight: 600, cursor: 'pointer',
                          }}>Yes</button>
                        <button
                          onClick={() => setAgentixSteps(prev => [...prev, { type: 'declined' }])}
                          style={{
                            background: 'none', color: 'var(--text-muted)',
                            border: '1px solid var(--border-light)', borderRadius: 4, padding: '5px 14px',
                            fontSize: 12, cursor: 'pointer',
                          }}>No</button>
                      </div>
                    </div>
                  )
                }
                if (step.type === 'approved') {
                  const h = step.hash
                  return (
                    <div key={i} style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
                      <div style={{ fontSize: 12, color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: 6 }}>
                        <StepDone /> Endpoint Investigation
                      </div>
                      <div style={{ fontSize: 12.5, color: 'var(--text-secondary)', paddingLeft: 14 }}>
                        The file hash{' '}
                        <code style={{ fontFamily: 'monospace', fontSize: 11, color: 'var(--accent-blue)' }}>{h}</code>{' '}
                        has been successfully added to the blocklist.
                      </div>
                      <div style={{ height: 10 }} />
                      <div style={{ fontSize: 12.5, color: 'var(--text-secondary)', paddingLeft: 14 }}>
                        <b style={{ color: 'var(--accent-green)' }}>Request Completion</b>
                      </div>
                      <div style={{ fontSize: 12.5, color: 'var(--text-muted)', paddingLeft: 14 }}>
                        Your request was successfully fulfilled — the specified file hash has been blocked.
                      </div>
                      <div style={{ fontSize: 12, color: 'var(--text-muted)', paddingLeft: 14 }}>
                        Dec 16th 2025 14:28:56
                      </div>
                    </div>
                  )
                }
                if (step.type === 'declined') {
                  return (
                    <div key={i} style={{ fontSize: 12, color: 'var(--text-muted)', paddingLeft: 14 }}>
                      Action cancelled. No changes were made.
                    </div>
                  )
                }
                return null
              })}
            </div>

            {/* Input bar */}
            <div style={{
              display: 'flex', alignItems: 'center', gap: 8,
              padding: '12px 16px',
              borderTop: '1px solid #1a2535',
              flexShrink: 0,
            }}>
              <input
                value={agentixInput}
                onChange={e => setAgentixInput(e.target.value)}
                onKeyDown={e => { if (e.key === 'Enter') sendAgentix() }}
                placeholder="Ask Endpoint Investigation agent anything or press '/' to navigate"
                style={{
                  flex: 1,
                  background: 'var(--bg-card2)',
                  border: '1px solid var(--border-light)',
                  borderRadius: 20,
                  padding: '8px 14px',
                  color: 'var(--text-secondary)',
                  fontSize: 12,
                  outline: 'none',
                }}
              />
              <button
                onClick={sendAgentix}
                style={{
                  width: 32, height: 32,
                  background: '#0078d4', border: 'none', borderRadius: '50%',
                  color: '#001a12', fontSize: 16,
                  cursor: 'pointer', display: 'flex', alignItems: 'center', justifyContent: 'center',
                  flexShrink: 0,
                }}>↑</button>
            </div>
          </div>
        </>
      )}

      {/* ── Keyframe injection for spinner animations ── */}
      <style>{`
        @keyframes xsiam-spin { to { transform: rotate(360deg); } }
        @keyframes xsiam-spin-rev { to { transform: rotate(-360deg); } }
      `}</style>

    </div>
  )
}

// ── Small helper components ───────────────────────────────────────────────────

function AgentixSpinner() {
  return (
    <div style={{
      width: 48, height: 48, borderRadius: '50%',
      border: '2px solid #00c89622',
      borderTopColor: '#0078d4',
      animation: 'xsiam-spin 1.5s linear infinite',
      position: 'relative',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
    }}>
      <div style={{
        width: 32, height: 32, borderRadius: '50%',
        border: '1.5px solid #00c89633',
        borderTopColor: '#00c896aa',
        animation: 'xsiam-spin-rev 1s linear infinite',
        position: 'absolute',
      }} />
    </div>
  )
}

function StepSpinner() {
  return (
    <div style={{
      width: 14, height: 14, borderRadius: '50%',
      border: '1.5px solid #00c89633',
      borderTopColor: '#0078d4',
      animation: 'xsiam-spin .8s linear infinite',
      flexShrink: 0,
    }} />
  )
}

function StepDone() {
  return (
    <div style={{
      width: 14, height: 14, borderRadius: '50%',
      background: '#0078d4', display: 'flex',
      alignItems: 'center', justifyContent: 'center',
      fontSize: 9, color: '#001a12', flexShrink: 0,
    }}>✓</div>
  )
}

// ── Shared table cell styles ──────────────────────────────────────────────────

const thStyle: CSSProperties = {
  position: 'sticky', top: 0,
  background: 'var(--bg-card)',
  padding: '7px 10px',
  textAlign: 'left',
  fontSize: 10.5,
  fontWeight: 600,
  color: 'var(--text-muted)',
  textTransform: 'uppercase',
  letterSpacing: '.4px',
  borderBottom: '1px solid var(--border)',
  whiteSpace: 'nowrap',
  zIndex: 10,
}

const tdStyle: CSSProperties = {
  padding: '6px 10px',
  borderBottom: '1px solid var(--border)',
  color: 'var(--text-secondary)',
  verticalAlign: 'middle',
}

// suppress unused import warning — PageMeta is imported per spec
void (undefined as unknown as PageMeta)
